import { RestaurantRole } from '../generated/prisma/client.js'
import { prisma } from '../lib/prisma.js'

const restaurantJobs = [
  {
    restaurantName: 'Cafe Levinsky',
    role: RestaurantRole.waiter,
    location: 'Tel Aviv',
    area: 'Levinsky',
    description: 'Friendly neighborhood cafe looking for an energetic waiter.',
    requirements: 'Good communication and a service-oriented attitude.',
    shiftInfo: 'Morning and afternoon shifts',
    contactPhone: '03-555-0101',
    contactWhatsapp: '972505550101',
  },
  {
    restaurantName: 'Rothschild Bar',
    role: RestaurantRole.bartender,
    location: 'Tel Aviv',
    area: 'Rothschild',
    description: 'Busy cocktail bar hiring a bartender for evening service.',
    requirements: 'Previous bar experience is preferred.',
    shiftInfo: 'Evening and weekend shifts',
    contactWhatsapp: '972505550102',
  },
  {
    restaurantName: 'Jaffa Bistro',
    role: RestaurantRole.host,
    location: 'Jaffa',
    area: 'Old Jaffa',
    description: 'Welcome guests and manage reservations at a lively bistro.',
    requirements: 'Organized, warm, and comfortable speaking with guests.',
    shiftInfo: 'Evening shifts',
    contactPhone: '03-555-0103',
  },
  {
    restaurantName: 'Dizengoff Grill',
    role: RestaurantRole.cook,
    location: 'Tel Aviv',
    area: 'Dizengoff',
    description: 'Join a fast-moving grill kitchen in central Tel Aviv.',
    requirements: 'Basic kitchen experience and ability to work under pressure.',
    shiftInfo: 'Flexible day and evening shifts',
    contactWhatsapp: '972505550104',
  },
  {
    restaurantName: 'Florentin Kitchen',
    role: RestaurantRole.floorManager,
    location: 'Tel Aviv',
    area: 'Florentin',
    description: 'Lead the floor team in a casual neighborhood restaurant.',
    requirements: 'Restaurant leadership experience and strong people skills.',
    shiftInfo: 'Five shifts per week',
    contactPhone: '03-555-0105',
  },
  {
    restaurantName: 'Morning People',
    role: RestaurantRole.waiter,
    location: 'Tel Aviv',
    area: 'Dizengoff',
    description: 'Popular brunch spot seeking a cheerful waiter.',
    requirements: 'Availability on Fridays and Saturdays.',
    shiftInfo: 'Morning shifts',
    contactWhatsapp: '972505550106',
  },
  {
    restaurantName: 'The Green Shaker',
    role: RestaurantRole.bartender,
    location: 'Tel Aviv',
    area: 'Florentin',
    description: 'Small local bar with a relaxed team and busy nights.',
    requirements: 'Cocktail knowledge is an advantage.',
    shiftInfo: 'Three to five evening shifts',
    contactPhone: '03-555-0107',
  },
  {
    restaurantName: 'Herzl Table',
    role: RestaurantRole.host,
    location: 'Tel Aviv',
    area: 'Florentin',
    description: 'Host guests and support smooth table turnover.',
    requirements: 'Strong communication and basic English.',
    shiftInfo: 'Evening shifts',
    contactWhatsapp: '972505550108',
  },
  {
    restaurantName: 'Port Oven',
    role: RestaurantRole.cook,
    location: 'Tel Aviv',
    area: 'Tel Aviv Port',
    description: 'Prepare fresh Mediterranean dishes in an open kitchen.',
    requirements: 'One year of kitchen experience is preferred.',
    shiftInfo: 'Full-time or part-time',
    contactPhone: '03-555-0109',
  },
  {
    restaurantName: 'Ramat Gan Social',
    role: RestaurantRole.floorManager,
    location: 'Ramat Gan',
    area: 'Bursa',
    description: 'Manage daily floor operations and support the service team.',
    requirements: 'At least one year in a shift-management role.',
    shiftInfo: 'Evenings and weekends',
    contactWhatsapp: '972505550110',
  },
  {
    restaurantName: 'Givatayim Corner',
    role: RestaurantRole.waiter,
    location: 'Givatayim',
    area: 'Katznelson',
    description: 'Community cafe looking for a reliable waiter.',
    requirements: 'No experience required; training is provided.',
    shiftInfo: 'Flexible weekly schedule',
    contactPhone: '03-555-0111',
  },
  {
    restaurantName: 'Marina Drinks',
    role: RestaurantRole.bartender,
    location: 'Herzliya',
    area: 'Herzliya Marina',
    description: 'Waterfront restaurant hiring for its bar team.',
    requirements: 'Service experience and weekend availability.',
    shiftInfo: 'Evenings and weekends',
    contactWhatsapp: '972505550112',
  },
  {
    restaurantName: 'Jaffa Courtyard',
    role: RestaurantRole.host,
    location: 'Jaffa',
    area: 'Flea Market',
    description: 'Create a welcoming first impression at a busy courtyard venue.',
    requirements: 'Friendly, composed, and organized.',
    shiftInfo: 'Four evening shifts',
    contactPhone: '03-555-0113',
  },
  {
    restaurantName: 'Levinsky Bakery',
    role: RestaurantRole.cook,
    location: 'Tel Aviv',
    area: 'Levinsky',
    description: 'Prepare sandwiches, salads, and light cafe dishes.',
    requirements: 'Early-morning availability.',
    shiftInfo: 'Morning shifts from 06:00',
    contactWhatsapp: '972505550114',
  },
  {
    restaurantName: 'Bialik House Cafe',
    role: RestaurantRole.floorManager,
    location: 'Tel Aviv',
    area: 'City Center',
    description: 'Coordinate service and shifts in a calm daytime cafe.',
    requirements: 'Previous floor or shift-management experience.',
    shiftInfo: 'Daytime shifts',
    contactPhone: '03-555-0115',
  },
  {
    restaurantName: 'Rothschild Brasserie',
    role: RestaurantRole.waiter,
    location: 'Tel Aviv',
    area: 'Rothschild',
    description: 'Professional service role in a high-volume brasserie.',
    requirements: 'At least six months of restaurant experience.',
    shiftInfo: 'Lunch and dinner shifts',
    contactWhatsapp: '972505550116',
  },
  {
    restaurantName: 'Jaffa Sunset',
    role: RestaurantRole.bartender,
    location: 'Jaffa',
    area: 'Jaffa Port',
    description: 'Mix drinks at a casual bar overlooking the sea.',
    requirements: 'Bartending course or practical experience.',
    shiftInfo: 'Late afternoon and evening',
    contactPhone: '03-555-0117',
  },
  {
    restaurantName: 'Garden Room',
    role: RestaurantRole.host,
    location: 'Givatayim',
    area: 'Borochov',
    description: 'Manage reservations and greet guests in a neighborhood venue.',
    requirements: 'Clear communication and attention to detail.',
    shiftInfo: 'Part-time evenings',
    contactWhatsapp: '972505550118',
  },
  {
    restaurantName: 'Herzliya Pasta Lab',
    role: RestaurantRole.cook,
    location: 'Herzliya',
    area: 'Industrial Area',
    description: 'Support fresh pasta preparation and dinner service.',
    requirements: 'Kitchen experience is helpful but not required.',
    shiftInfo: 'Afternoon and evening shifts',
    contactPhone: '09-555-0119',
  },
  {
    restaurantName: 'Urban Plate',
    role: RestaurantRole.floorManager,
    location: 'Ramat Gan',
    area: 'City Center',
    description: 'Run shifts and maintain a warm guest experience.',
    requirements: 'Leadership skills and restaurant service experience.',
    shiftInfo: 'Full-time rotating shifts',
    contactWhatsapp: '972505550120',
  },
  {
    restaurantName: 'Cafe Nordau',
    role: RestaurantRole.waiter,
    location: 'Tel Aviv',
    area: 'Old North',
    description: 'Join a friendly local cafe serving breakfast and lunch.',
    requirements: 'Positive attitude and weekend availability.',
    shiftInfo: 'Morning and lunch shifts',
    contactPhone: '03-555-0121',
  },
  {
    restaurantName: 'Allenby Night',
    role: RestaurantRole.bartender,
    location: 'Tel Aviv',
    area: 'Allenby',
    description: 'Fast-paced bar looking for an experienced night bartender.',
    requirements: 'At least one year behind a busy bar.',
    shiftInfo: 'Night shifts',
    contactWhatsapp: '972505550122',
  },
  {
    restaurantName: 'Ramat Gan Terrace',
    role: RestaurantRole.host,
    location: 'Ramat Gan',
    area: 'Marom Nave',
    description: 'Welcome families and manage the evening reservation list.',
    requirements: 'Patient and service-minded.',
    shiftInfo: 'Evenings and weekends',
    contactPhone: '03-555-0123',
  },
  {
    restaurantName: 'Shuk Kitchen',
    role: RestaurantRole.cook,
    location: 'Tel Aviv',
    area: 'Carmel Market',
    description: 'Cook fresh market dishes in a compact open kitchen.',
    requirements: 'Comfortable with prep and line work.',
    shiftInfo: 'Day and evening shifts',
    contactWhatsapp: '972505550124',
  },
  {
    restaurantName: 'Dizengoff Dining',
    role: RestaurantRole.floorManager,
    location: 'Tel Aviv',
    area: 'Dizengoff',
    description: 'Supervise service at a polished but relaxed restaurant.',
    requirements: 'Two years of restaurant experience.',
    shiftInfo: 'Full-time',
    contactPhone: '03-555-0125',
  },
  {
    restaurantName: 'Jaffa Breakfast Club',
    role: RestaurantRole.waiter,
    location: 'Jaffa',
    area: 'Noga',
    description: 'Serve breakfast and coffee in a creative neighborhood cafe.',
    requirements: 'Early availability and conversational English.',
    shiftInfo: 'Morning shifts',
    contactWhatsapp: '972505550126',
  },
  {
    restaurantName: 'Givatayim Taproom',
    role: RestaurantRole.bartender,
    location: 'Givatayim',
    area: 'Katznelson',
    description: 'Pour local beer and simple cocktails in a neighborhood taproom.',
    requirements: 'Bar experience is preferred.',
    shiftInfo: 'Evening shifts',
    contactPhone: '03-555-0127',
  },
  {
    restaurantName: 'Marina Welcome',
    role: RestaurantRole.host,
    location: 'Herzliya',
    area: 'Herzliya Marina',
    description: 'Coordinate reservations at a busy waterfront restaurant.',
    requirements: 'Professional communication and weekend availability.',
    shiftInfo: 'Lunch and dinner shifts',
    contactWhatsapp: '972505550128',
  },
  {
    restaurantName: 'Florentin Fire',
    role: RestaurantRole.cook,
    location: 'Tel Aviv',
    area: 'Florentin',
    description: 'Work the grill and prep station in a casual late-night kitchen.',
    requirements: 'Previous line-cook experience.',
    shiftInfo: 'Evening and night shifts',
    contactPhone: '03-555-0129',
  },
  {
    restaurantName: 'Herzliya Beach House',
    role: RestaurantRole.floorManager,
    location: 'Herzliya',
    area: 'Beachfront',
    description: 'Lead a young service team at a busy beach restaurant.',
    requirements: 'Shift-management experience and strong availability.',
    shiftInfo: 'Full-time including weekends',
    contactWhatsapp: '972505550130',
  },
]

async function seedRestaurantJobs() {
  let createdCount = 0

  for (const job of restaurantJobs) {
    const existingJob = await prisma.restaurantJob.findFirst({
      where: {
        restaurantName: job.restaurantName,
        role: job.role,
        location: job.location,
      },
      select: {
        id: true,
      },
    })

    if (!existingJob) {
      await prisma.restaurantJob.create({
        data: job,
      })
      createdCount += 1
    }
  }

  console.log(
    `Restaurant job seed complete: ${createdCount} created, ${
      restaurantJobs.length - createdCount
    } already existed.`,
  )
}

try {
  await seedRestaurantJobs()
} catch (error) {
  console.error('Failed to seed restaurant jobs:', error)
  process.exitCode = 1
} finally {
  await prisma.$disconnect()
}
